/**
 * ATS PDF Text Layer Injection & Sanitization Utility
 * 
 * Ensures PDFs generated from HTML canvases contain 100% genuine vector
 * selectable text streams readable by ATS systems (Workday, Taleo, Greenhouse,
 * Bullhorn, pdfplumber, pdfminer, etc.) with zero blank page overflows.
 */

/**
 * Sanitizes text strings for standard PDF font encoding (Helvetica/WinAnsi).
 * Normalizes Unicode diacritics (accents), standardizes dashes, quotes and bullet points,
 * and strips emojis/icons that cause corrupt replacement glyphs in ATS parsers.
 * 
 * @param {string} str - Raw string
 * @returns {string} Sanitized string safe for ATS keyword parsing
 */
export function sanitizeAtsText(str) {
  if (!str) return ''
  return str
    // Standardize bullet points
    .replace(/[\u2022\u25cf\u25cb\u25aa\u25ab\u2043\u2219]/g, '- ')
    // Standardize dashes & hyphens
    .replace(/[\u2010\u2011\u2012\u2013\u2014\u2015\u2212]/g, '-')
    // Standardize quotes
    .replace(/[\u2018\u2019\u201a\u201b]/g, "'")
    .replace(/[\u201c\u201d\u201e\u201f]/g, '"')
    // Non-breaking spaces and zero-width spaces
    .replace(/[\u00a0\u200b\u200c\u200d\ufeff]/g, ' ')
    // Strip common emojis / icons (phone, mail, pin, etc.)
    .replace(/[\u{1F300}-\u{1FAD6}\u{1F600}-\u{1F64F}\u{1F680}-\u{1F6FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu, ' ')
    // Normalize diacritics (e.g., 'Educación' -> 'Educacion') for 100% clean ASCII ATS parsing
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    // Replace remaining non-printable / non-standard characters with space
    .replace(/[^\x20-\x7E\r\n\t]/g, ' ')
    // Collapse multi-spaces
    .replace(/[ \t]+/g, ' ')
    .trim()
}

/**
 * Injects an invisible vector text layer into a jsPDF document positioned
 * directly over the visual elements rendered from the DOM.
 * 
 * @param {object} pdf - jsPDF document instance
 * @param {HTMLElement} element - Root DOM container of the resume
 * @param {object} data - Structured resume data (fallback/metadata)
 */
export function injectAtsTextLayer(pdf, element, data = {}) {
  if (!pdf || !element) return

  const elementRect = element.getBoundingClientRect()
  if (!elementRect.width || !elementRect.height) return

  const totalPages = pdf.internal.getNumberOfPages()

  // Letter standard: 8.5 x 11 inches. 816px width = 8.5in at 96 DPI.
  const scaleX = 8.5 / (elementRect.width || 816)
  const scaleY = 11.0 / 1056

  // Walk all DOM text nodes
  const walker = document.createTreeWalker(
    element,
    NodeFilter.SHOW_TEXT,
    {
      acceptNode: (node) => {
        if (!node.nodeValue || !node.nodeValue.trim()) {
          return NodeFilter.FILTER_REJECT
        }
        const parent = node.parentElement
        if (!parent) return NodeFilter.FILTER_REJECT

        const tag = parent.tagName.toLowerCase()
        if (tag === 'script' || tag === 'style' || tag === 'noscript') {
          return NodeFilter.FILTER_REJECT
        }

        const style = window.getComputedStyle(parent)
        if (
          style.display === 'none' ||
          style.visibility === 'hidden' ||
          style.opacity === '0'
        ) {
          return NodeFilter.FILTER_REJECT
        }

        return NodeFilter.FILTER_ACCEPT
      }
    }
  )

  const range = document.createRange()
  let currentNode = walker.nextNode()

  while (currentNode) {
    const rawText = currentNode.nodeValue
    const cleanText = sanitizeAtsText(rawText)

    if (cleanText.length > 0) {
      try {
        range.selectNodeContents(currentNode)
        const rect = range.getBoundingClientRect()

        if (rect.width > 0 && rect.height > 0) {
          // Calculate coordinates in inches relative to the element
          const xInches = (rect.left - elementRect.left) * scaleX
          const yTotalInches = (rect.top - elementRect.top) * scaleY

          const parentEl = currentNode.parentElement
          const parentStyle = window.getComputedStyle(parentEl)
          const fontSizePx = parseFloat(parentStyle.fontSize) || 12
          const fontSizePt = Math.max(6, Math.min(22, Math.round(fontSizePx * 0.75)))
          const isBold = /bold|[6-9]00/.test(parentStyle.fontWeight)

          // Determine page index (1-based)
          let pageIndex = Math.floor(yTotalInches / 11.0) + 1
          // Clamp to actual pages generated by html2pdf so we NEVER create an extra blank page
          if (pageIndex > totalPages) {
            pageIndex = totalPages
          }

          // Compute Y coordinate on the target page
          const pageYInches = (yTotalInches % 11.0) + (fontSizePt / 72) * 0.9

          // Safe bounds check within Letter sheet (margin allowance)
          if (
            xInches >= 0.1 &&
            xInches <= 8.4 &&
            pageYInches >= 0.1 &&
            pageYInches <= 10.9
          ) {
            pdf.setPage(pageIndex)
            pdf.setFont('helvetica', isBold ? 'bold' : 'normal')
            pdf.setFontSize(fontSizePt)

            const isMultiLine = rect.height > fontSizePx * 1.6
            if (isMultiLine) {
              const maxWidthInches = Math.min(7.5, (rect.width * scaleX) + 0.1)
              pdf.text(cleanText, xInches, pageYInches, {
                maxWidth: maxWidthInches,
                renderingMode: 'invisible'
              })
            } else {
              pdf.text(cleanText, xInches, pageYInches, {
                renderingMode: 'invisible'
              })
            }
          }
        }
      } catch (nodeErr) {
        // Silently continue to next node if bounding rect fails
      }
    }

    currentNode = walker.nextNode()
  }

  // Set standard PDF document properties for ATS identification
  const candidateName = (data?.personal_info?.name || 'Resume').trim()
  pdf.setProperties({
    title: `${candidateName} - ATS Resume`,
    subject: JSON.stringify(data),
    author: 'ATS Resume Generator',
    creator: 'smart507 ATS Resume Generator'
  })
}

